### ISSUE TITLE
error while running lambda code

### ISSUE THREAD

**Issue by Prasadpb77** [aws-samples/cloudwatch-custom-widgets-samples#1]
{
  "errorMessage": "'widgetContext'",
  "errorType": "KeyError",
  "stackTrace": [
    "  File \"/var/task/index.py\", line 59, in lambda_handler\n    form = event['widgetContext']['forms']['all']\n"
  ]
}

**Comment by Gringox** [comment]
Questions:

- How did you run this function? It is meant to be run as part of a Custom Widget not by its own

- What sample are you trying to run?
