### ISSUE TITLE
Python templates fail to deploy due to use of Python 3.7

### ISSUE THREAD

**Issue by HieronymusLex** [aws-samples/cloudwatch-custom-widgets-samples#4]
I tried deploying the RSS reader Python sample widget however the stack fails to create due to the use of Python 3.7 with the error message `The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.12) while creating or updating functions.`

The [build-assets](https://github.com/aws-samples/cloudwatch-custom-widgets-samples/blob/main/scripts/build-assets#L40) script needs to be updated to use a more recent version of Python. I've confirmed the RSS Reader works with 3.12 but I haven't regression tested the other sample widgets

**Comment by Gringox** [comment]
Thanks for reporting this, we are looking into updating the script
